// Shared design library data — included by designs.html and designer.html
const DESIGN_CATS = [
  {key:'all',          label:'All'},
  {key:'boots',        label:'Boots on the Ground'},
  {key:'funprint',     label:'Fun Print'},
  {key:'women',        label:'Women · Denim Boss Lady'},
  {key:'anime',        label:'Anime'},
];

const DESIGN_LIBRARY = {
  boots: [
    {id:"boots/boots-main",name:"Boots on the Ground"},
    {id:"boots/boots-1",name:"Boots 1"},
    {id:"boots/boots-2",name:"Boots 2"},
    {id:"boots/boots-3",name:"Boots 3"},
    {id:"boots/boots-4",name:"Boots 4"},
    {id:"boots/boots-5",name:"Boots 5"},
    {id:"boots/boots-6",name:"Boots 6"},
    {id:"boots/boots-7",name:"Boots 7"},
    {id:"boots/boots-8",name:"Boots 8"},
    {id:"boots/boots-9",name:"Boots 9"},
    {id:"boots/boots-10",name:"Boots 10"},
    {id:"boots/boots-11",name:"Boots 11"},
    {id:"boots/boots-12",name:"Boots 12"},
    {id:"boots/boots-13",name:"Boots 13"},
    {id:"boots/boots-14",name:"Boots 14"},
    {id:608304386,name:"Boots Series 1"},
    {id:608307586,name:"Boots Series 2"},
    {id:608307846,name:"Boots Series 3"},
    {id:608307951,name:"Boots Series 4"},
    {id:608315661,name:"No Kings In America"},
    {id:608316616,name:"No Kings — We The People"},
    {id:608316681,name:"No Kings — Political"},
    {id:608316811,name:"No Kings — Anti Trump"},
    {id:608317016,name:"No Kings — VTN"},
    {id:608317136,name:"No Kings — Patriot"},
    {id:608317226,name:"We The People — LGBT"},
    {id:608317341,name:"No Kings — NHUY"},
    {id:608317481,name:"No Kings — VTN 2"},
    {id:608317621,name:"We Have No Kings"},
    {id:608317711,name:"Floral Boho No Kings"},
    {id:608317761,name:"Floral Boho Since 1776"},
    {id:608317826,name:"No Kings — Classic"},
    {id:608317961,name:"No Kings — Bold"},
    {id:608318096,name:"No Kings Since 1776"},
    {id:608318266,name:"Please Take Them"},
    {id:608318356,name:"No Kings — VTN 3"},
    {id:608318446,name:"We Have No Kings — VTN 2"},
    {id:608318531,name:"No Kings — NHUY 2"},
    {id:615015311,name:"Heritage — Don't Recognize My Party"},
    {id:615015546,name:"Heritage — Look What They Did"},
    {id:615015666,name:"Heritage — Hijacked"},
    {id:615015746,name:"Heritage — Party"},
    {id:624741461,name:"Woman of My Dreams — Pink & Green"},
    {id:624741551,name:"Woman of My Dreams — Variant"},
    {id:625485816,name:"Black Front"},
    {id:625486171,name:"Black Front 2"},
    {id:625487091,name:"White Front"},
    {id:625487166,name:"White Back"},
    {id:625489876,name:"Black Front 3"},
    {id:625489956,name:"Black Back"},
    {id:626103671,name:"Fishers of Men"},
  ],
  funprint: [
    {id:"funprint/Culture.png",              name:"Culture"},
    {id:"funprint/HERE WE GO PNG.png",       name:"Here We Go"},
    {id:"funprint/HUSTLE HARD.png",          name:"Hustle Hard"},
    {id:"funprint/i need a hug black.png",   name:"I Need a Hug (Black)"},
    {id:"funprint/i need a hug.png",         name:"I Need a Hug"},
    {id:"funprint/LIPS.png",                 name:"Lips"},
    {id:"funprint/Swallow.png",              name:"Swallow"},
    {id:"funprint/THICK-FIL-A.png",          name:"Thick-Fil-A"},
    {id:"funprint/THICKERTHANASNICKER.png",  name:"Thicker Than a Snicker"},
    {id:"funprint/TIRED.png",                name:"Tired"},
  ],
  women: [
    {id:"women-denim/1.png",name:"Denim Boss Lady 1"},
    {id:"women-denim/2.png",name:"Denim Boss Lady 2"},
    {id:"women-denim/3.png",name:"Denim Boss Lady 3"},
    {id:"women-denim/4.png",name:"Denim Boss Lady 4"},
    {id:"women-denim/5.png",name:"Denim Boss Lady 5"},
    {id:"women-denim/6.png",name:"Denim Boss Lady 6"},
    {id:"women-denim/7.png",name:"Denim Boss Lady 7"},
    {id:"women-denim/8.png",name:"Denim Boss Lady 8"},
    {id:"women-denim/9.png",name:"Denim Boss Lady 9"},
    {id:"women-denim/10.png",name:"Denim Boss Lady 10"},
    {id:"women-denim/11.png",name:"Denim Boss Lady 11"},
    {id:"women-denim/12.png",name:"Denim Boss Lady 12"},
    {id:"women-denim/13.png",name:"Denim Boss Lady 13"},
    {id:"women-denim/14.png",name:"Denim Boss Lady 14"},
    {id:"women-denim/15.png",name:"Denim Boss Lady 15"},
    {id:"women-denim/16.png",name:"Denim Boss Lady 16"},
    {id:"women-denim/17.png",name:"Denim Boss Lady 17"},
    {id:"women-denim/18.png",name:"Denim Boss Lady 18"},
    {id:"women-denim/19.png",name:"Denim Boss Lady 19"},
    {id:"women-denim/20.png",name:"Denim Boss Lady 20"},
    {id:"women-denim/21.png",name:"Denim Boss Lady 21"},
    {id:"women-denim/22.png",name:"Denim Boss Lady 22"},
    {id:"women-denim/23.png",name:"Denim Boss Lady 23"},
    {id:"women-denim/24.png",name:"Denim Boss Lady 24"},
    {id:"women-denim/25.png",name:"Denim Boss Lady 25"},
    {id:"women-denim/26.png",name:"Denim Boss Lady 26"},
    {id:"women-denim/27.png",name:"Denim Boss Lady 27"},
    {id:"women-denim/28.png",name:"Denim Boss Lady 28"},
    {id:"women-denim/29.png",name:"Denim Boss Lady 29"},
    {id:"women-denim/30.png",name:"Denim Boss Lady 30"},
    {id:"women-denim/31.png",name:"Denim Boss Lady 31"},
    {id:"women-denim/32.png",name:"Denim Boss Lady 32"},
    {id:"women-denim/33.png",name:"Denim Boss Lady 33"},
    {id:"women-denim/34.png",name:"Denim Boss Lady 34"},
    {id:"women-denim/35.png",name:"Denim Boss Lady 35"},
    {id:"women-denim/36.png",name:"Denim Boss Lady 36"},
    {id:"women-denim/37.png",name:"Denim Boss Lady 37"},
    {id:"women-denim/38.png",name:"Denim Boss Lady 38"},
    {id:"women-denim/39.png",name:"Denim Boss Lady 39"},
    {id:"women-denim/40.png",name:"Denim Boss Lady 40"},
    {id:"women-denim/41.png",name:"Denim Boss Lady 41"},
    {id:"women-denim/42.png",name:"Denim Boss Lady 42"},
    {id:"women-denim/43.png",name:"Denim Boss Lady 43"},
    {id:"women-denim/44.png",name:"Denim Boss Lady 44"},
    {id:"women-denim/45.png",name:"Denim Boss Lady 45"},
    {id:"women-denim/46.png",name:"Denim Boss Lady 46"},
    {id:"women-denim/47.png",name:"Denim Boss Lady 47"},
    {id:"women-denim/48.png",name:"Denim Boss Lady 48"},
    {id:"women-denim/49.png",name:"Denim Boss Lady 49"},
    {id:"women-denim/50.png",name:"Denim Boss Lady 50"},
    {id:"women-denim/51.png",name:"Denim Boss Lady 51"},
    {id:"women-denim/52.png",name:"Denim Boss Lady 52"},
    {id:"women-denim/53.png",name:"Denim Boss Lady 53"},
    {id:"women-denim/54.png",name:"Denim Boss Lady 54"},
    {id:"women-denim/55.png",name:"Denim Boss Lady 55"},
    {id:"women-denim/56.png",name:"Denim Boss Lady 56"},
    {id:"women-denim/57.png",name:"Denim Boss Lady 57"},
    {id:"women-denim/58.png",name:"Denim Boss Lady 58"},
    {id:"women-denim/59.png",name:"Denim Boss Lady 59"},
    {id:"women-denim/60.png",name:"Denim Boss Lady 60"},
    {id:"women-denim/61.png",name:"Denim Boss Lady 61"},
    {id:"women-denim/62.png",name:"Denim Boss Lady 62"},
    {id:"women-denim/63.png",name:"Denim Boss Lady 63"},
    {id:"women-denim/64.png",name:"Denim Boss Lady 64"},
  ],
  anime: [
    {id:"anime/ANIME V2 OK-01-01 (1).png", name:"Anime V2 OK-01"},
    {id:"anime/ANIME V2 OK-02-01 (1).png", name:"Anime V2 OK-02"},
    {id:"anime/ANIME V2 OK-03-01 (1).png", name:"Anime V2 OK-03"},
    {id:"anime/ANIME V2 OK-04-01 (1).png", name:"Anime V2 OK-04"},
    {id:"anime/ANIME V2 OK-05-01 (1).png", name:"Anime V2 OK-05"},
    {id:"anime/ANIME V2 OK-06-01 (1).png", name:"Anime V2 OK-06"},
    {id:"anime/ANIME V2 OK-07-01 (1).png", name:"Anime V2 OK-07"},
    {id:"anime/ANIME V2 OK-08-01 (1).png", name:"Anime V2 OK-08"},
    {id:"anime/ANIME V2 OK-09 (1).png",    name:"Anime V2 OK-09"},
    {id:"anime/ANIME V2 OK-10-01 (1).png", name:"Anime V2 OK-10"},
    {id:"anime/ANIME V2 OK-11-01 (1).png", name:"Anime V2 OK-11"},
    {id:"anime/ANIME V2 OK-12-01 (1).png", name:"Anime V2 OK-12"},
    {id:"anime/ANIME V2 OK-13-01 (1).png", name:"Anime V2 OK-13"},
    {id:"anime/ANIME V2 OK-40 (1).png",    name:"Anime V2 OK-40"},
    {id:"anime/ANIME V2 OK-61-01 (1).png", name:"Anime V2 OK-61"},
    {id:"anime/ANIME V2 OK-62-01 (1).png", name:"Anime V2 OK-62"},
    {id:"anime/NARUTO-01 (1).png",  name:"Naruto 01"},
    {id:"anime/NARUTO-02 (1).png",  name:"Naruto 02"},
    {id:"anime/NARUTO-03 (1).png",  name:"Naruto 03"},
    {id:"anime/NARUTO-04 (1).png",  name:"Naruto 04"},
    {id:"anime/NARUTO-05 (1).png",  name:"Naruto 05"},
    {id:"anime/NARUTO-06 (1).png",  name:"Naruto 06"},
    {id:"anime/NARUTO-07 (1).png",  name:"Naruto 07"},
    {id:"anime/NARUTO-08 (1).png",  name:"Naruto 08"},
    {id:"anime/NARUTO-09 (1).png",  name:"Naruto 09"},
    {id:"anime/NARUTO-10 (1).png",  name:"Naruto 10"},
    {id:"anime/NARUTO-11 (1).png",  name:"Naruto 11"},
    {id:"anime/NARUTO-12 (1).png",  name:"Naruto 12"},
    {id:"anime/NARUTO-13 (1).png",  name:"Naruto 13"},
    {id:"anime/NARUTO-14 (1).png",  name:"Naruto 14"},
    {id:"anime/NARUTO-15 (1).png",  name:"Naruto 15"},
    {id:"anime/NARUTO-16 (1).png",  name:"Naruto 16"},
    {id:"anime/NARUTO-17 (1).png",  name:"Naruto 17"},
    {id:"anime/NARUTO-18 (1).png",  name:"Naruto 18"},
    {id:"anime/NARUTO-19 (1).png",  name:"Naruto 19"},
    {id:"anime/NARUTO-20 (1).png",  name:"Naruto 20"},
    {id:"anime/NARUTO-21 (1).png",  name:"Naruto 21"},
    {id:"anime/NARUTO-22 (1).png",  name:"Naruto 22"},
    {id:"anime/NARUTO-23 (1).png",  name:"Naruto 23"},
    {id:"anime/NARUTO-24 (1).png",  name:"Naruto 24"},
    {id:"anime/NARUTO-25 (1).png",  name:"Naruto 25"},
  ],
};

// Flat array with cat key on each item
const ALL_LIBRARY_DESIGNS = [];
for (const [cat, items] of Object.entries(DESIGN_LIBRARY)) {
  items.forEach(d => ALL_LIBRARY_DESIGNS.push({...d, cat}));
}

function designImgUrl(id) {
  return 'design-images/' + (/\.\w+$/.test(id) ? id : id + '.png');
}
function designImgFallback(id) {
  // Try without www (SSL cert covers vistecprints.com, not www.)
  return 'https://vistecprints.com/aimages/' + id + '/1/0/design.jpg';
}
function designImgFallback2(id) {
  // Last resort: transparent 1×1 so onerror doesn't loop
  return 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7';
}
function designCatLabel(key) {
  return DESIGN_CATS.find(c => c.key === key)?.label || key;
}
