name: Deploy to HostGator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger cPanel Git Pull + Deploy
        run: |
          curl -s -k \
            -u "${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }}" \
            "https://gator3045.hostgator.com:2083/execute/VersionControl/update" \
            --data "repository_root=/home3/vistecpr/vistecprints-git"
          curl -s -k \
            -u "${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }}" \
            "https://gator3045.hostgator.com:2083/execute/VersionControlDeployment/create" \
            --data "repository_root=/home3/vistecpr/vistecprints-git"
